services:
  postgres:
    image: postgres:16
    container_name: auth_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    container_name: auth_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/src

  redis:
    image: redis:latest
    container_name: auth_redis
    restart: always
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    container_name: auth_nginx
    depends_on:
      - fastapi
    ports:
      - "80:80"


volumes:
  postgres_data:
