# Generated by Django 4.2.11 on 2024-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.TextField(
                blank=True,
                choices=[("male", "male"), ("female", "female")],
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.TextField(
                blank=True,
                choices=[
                    ("director", "director"),
                    ("producer", "producer"),
                    ("actor", "actor"),
                    ("screenwriter", "screenwriter"),
                    ("operator", "operator"),
                    ("composer", "composer"),
                ],
                null=True,
                verbose_name="role",
            ),
        ),
    ]
