# Generated by Django 4.2.11 on 2024-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_person_gender_alter_personfilmwork_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={"verbose_name": "filmwork",
                     "verbose_name_plural": "filmworks"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "genre",
                     "verbose_name_plural": "genres"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "person",
                     "verbose_name_plural": "persons"},
        ),
        migrations.RemoveField(
            model_name="person",
            name="film_works",
        ),
        migrations.AddField(
            model_name="filmwork",
            name="persons",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="movies.PersonFilmwork",
                to="movies.person",
            ),
        ),
    ]
