# Generated by Django 4.2.11 on 2024-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_filmwork_options_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="viewing_permission",
            field=models.CharField(
                choices=[("FR", "free"), ("PR", "premium")],
                default="PR",
                max_length=255,
                verbose_name="viewing permission",
            ),
        ),
    ]
