# Generated by Django 4.2.11 on 2024-07-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_genrefilmwork_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer')], default='actor', max_length=20, verbose_name='role'),
        ),
    ]
