"""partitions

Revision ID: 020063ca7a2e
Revises: bb267e786aec
Create Date: 2024-09-14 19:19:07.898521

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "020063ca7a2e"
down_revision: Union[str, None] = "bb267e786aec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "login_history", ["id", "event_date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "login_history", type_="unique")
    # ### end Alembic commands ###
