"""update_user

Revision ID: 39a1ed7ca651
Revises: 55f240fba5b9
Create Date: 2024-09-14 21:14:42.783362

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39a1ed7ca651"
down_revision: Union[str, None] = "55f240fba5b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=250),
        nullable=False,
    )
    op.create_unique_constraint("login_email_unique", "users", ["login", "email"])
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint("login_email_unique", "users", type_="unique")
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###
