"""user_agent

Revision ID: bb267e786aec
Revises: 55f240fba5b9
Create Date: 2024-09-14 14:20:51.298602

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb267e786aec"
down_revision: Union[str, None] = "55f240fba5b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login_history", sa.Column("user_agent", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("login_history", "user_agent")
    # ### end Alembic commands ###
